version: "3.8"

services:
  library-api:
    build:
      context: ./library-api
      dockerfile: Dockerfile
    container_name: library-api
    ports:
      - "3000:3000"
    volumes:
      - ./library-api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_SECURE=false
      - SMTP_USER=
      - SMTP_PASS=
    restart: unless-stopped
    depends_on:
      - mailhog

  library-ui:
    build:
      context: ./library-ui
      dockerfile: Dockerfile
    container_name: library-ui
    ports:
      - "5173:5173"
    volumes:
      - ./library-ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - library-api
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server port
      - "8025:8025" # Web UI port
    restart: unless-stopped
