name: Library WEB CI

on:
  push:
    branches: [main]
    paths:
      - "library-web/**"
  pull_request:
    branches: [main]
    paths:
      - "library-web/**"

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: library-web

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "library-web/package-lock.json"

      - name: Install dependencies
        run: npm ci

      # Cache node_modules for use by other jobs
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: library-web/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('library-web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

  lint:
    name: Lint Code
    needs: install-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: library-web

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Restore cached node_modules
      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: library-web/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('library-web/package-lock.json') }}

      - name: Run linting
        run: npm run lint

  test:
    name: Run Tests
    needs: install-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: library-web

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Restore cached node_modules
      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: library-web/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('library-web/package-lock.json') }}

      - name: Run tests
        run: npm test

      # Generate and upload test coverage reports
      - name: Generate test coverage
        run: npm test -- --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: library-web/coverage
          retention-days: 7

  build:
    name: Build Application
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: library-web

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Restore cached node_modules
      - name: Restore node_modules cache
        uses: actions/cache@v3
        with:
          path: library-web/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('library-web/package-lock.json') }}

      - name: Build application
        run: npm run build

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: library-web/dist
          retention-days: 3
