name: Library API CI

on:
  push:
    branches: [main]
    paths:
      - "library-api/**"
  pull_request:
    branches: [main]
    paths:
      - "library-api/**"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: library-api
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "library-api/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: library-api/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('library-api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

  lint:
    needs: install-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: library-api
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "library-api/package-lock.json"

      - name: Restore node modules
        uses: actions/cache@v3
        with:
          path: library-api/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('library-api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Check code style with ESLint
        run: npx eslint . --ext .js,.ts

  test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: library-api
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "library-api/package-lock.json"

      - name: Restore node modules
        uses: actions/cache@v3
        with:
          path: library-api/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('library-api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Run tests
        run: npx jest

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: library-api
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "library-api/package-lock.json"

      - name: Restore node modules
        uses: actions/cache@v3
        with:
          path: library-api/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('library-api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Build project
        run: npm run build
