name: Library API CI

on:
  push:
    branches: [main]
    paths:
      - "library-api/**"
  pull_request:
    branches: [main]
    paths:
      - "library-api/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: library-api

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "library-api/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Check code style with ESLint
        run: |
          npm install eslint --no-save
          npx eslint . --ext .js,.ts

      - name: Build project
        run: npm run build

      - name: Setup test environment
        run: |
          npm install jest @types/jest ts-jest --no-save
          npm install supertest @types/supertest --no-save

      - name: Run tests
        run: |
          echo 'module.exports = { preset: "ts-jest", testEnvironment: "node", testMatch: ["**/__tests__/**/*.ts", "**/?(*.)+(spec|test).ts"] };' > jest.config.js
          npx jest
